version: "3.9"
services:
  app:
    build: .
    container_name: bot
    env_file: .env.docker
    depends_on:
      - db
    command: python main.py
    volumes:
      - .:/app

  db:
    image: postgres:latest
    container_name: jobs_db
    restart: always
    environment:
      POSTGRES_DB: jobs_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
