"""initial_schema

Revision ID: 801b4eb46f14
Revises: 
Create Date: 2025-07-27 16:18:35.671118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '801b4eb46f14'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_postings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=128), nullable=False),
    sa.Column('company_name', sa.String(length=128), nullable=False),
    sa.Column('job_link', sa.String(length=512), nullable=False),
    sa.Column('quick_description', sa.String(length=2048), nullable=True),
    sa.Column('company_type', sa.String(length=32), nullable=True),
    sa.Column('industry', sa.String(length=32), nullable=True),
    sa.Column('tech_stack', sa.String(length=256), nullable=True),
    sa.Column('stage', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_postings_id'), 'job_postings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_postings_id'), table_name='job_postings')
    op.drop_table('job_postings')
    # ### end Alembic commands ###
