"""candidate_language

Revision ID: 8d783b8e3aa7
Revises: 556d24ac2c86
Create Date: 2025-08-03 16:45:42.142309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d783b8e3aa7'
down_revision: Union[str, Sequence[str], None] = '556d24ac2c86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('language', sa.String(length=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'language')
    # ### end Alembic commands ###
