"""add_job_status_field

Revision ID: b403be2a2a78
Revises: 854a9eb89f00
Create Date: 2025-08-16 16:02:07.576729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b403be2a2a78'
down_revision: Union[str, Sequence[str], None] = '854a9eb89f00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_postings', sa.Column('status', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_postings', 'status')
    # ### end Alembic commands ###
