"""job_posting_enrichment

Revision ID: dc4be968c73b
Revises: 8d783b8e3aa7
Create Date: 2025-08-09 00:57:33.907999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc4be968c73b'
down_revision: Union[str, Sequence[str], None] = '8d783b8e3aa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_postings', sa.Column('detailed_description', sa.Text(), nullable=True))
    op.add_column('job_postings', sa.Column('requirements', sa.Text(), nullable=True))
    op.add_column('job_postings', sa.Column('benefits', sa.Text(), nullable=True))
    op.add_column('job_postings', sa.Column('salary_range', sa.String(length=255), nullable=True))
    op.add_column('job_postings', sa.Column('application_deadline', sa.DateTime(), nullable=True))
    op.add_column('job_postings', sa.Column('contact_info', sa.Text(), nullable=True))
    op.add_column('job_postings', sa.Column('enriched_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_postings', 'enriched_at')
    op.drop_column('job_postings', 'contact_info')
    op.drop_column('job_postings', 'application_deadline')
    op.drop_column('job_postings', 'salary_range')
    op.drop_column('job_postings', 'benefits')
    op.drop_column('job_postings', 'requirements')
    op.drop_column('job_postings', 'detailed_description')
    # ### end Alembic commands ###
