"""add_notified_at_to_matches

Revision ID: e5996f28c4f1
Revises: 3e27385024cf
Create Date: 2025-08-17 00:15:43.138135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5996f28c4f1'
down_revision: Union[str, Sequence[str], None] = '3e27385024cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('notified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'notified_at')
    # ### end Alembic commands ###
