import os
from dotenv import load_dotenv

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
SERPAPI_KEY = os.getenv("SERPAPI_KEY", "")
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "")

# Cron job configurations
CRON_JOB_SEEKER_INTERVAL_HOURS = int(os.getenv("CRON_JOB_SEEKER_INTERVAL_HOURS", "6"))
CRON_JOB_ENRICHMENT_INTERVAL_HOURS = int(os.getenv("CRON_JOB_ENRICHMENT_INTERVAL_HOURS", "12"))
CRON_NOTIFICATION_INTERVAL_HOURS = int(os.getenv("CRON_NOTIFICATION_INTERVAL_HOURS", "24"))
CRON_MATCH_NOTIFICATION_INTERVAL_HOURS = int(os.getenv("CRON_MATCH_NOTIFICATION_INTERVAL_HOURS", "24"))

# Cron job start times (24-hour format)
CRON_JOB_SEEKER_START_TIME = os.getenv("CRON_JOB_SEEKER_START_TIME", "00:00")
CRON_JOB_ENRICHMENT_START_TIME = os.getenv("CRON_JOB_ENRICHMENT_START_TIME", "02:00")
CRON_NOTIFICATION_START_TIME = os.getenv("CRON_NOTIFICATION_START_TIME", "08:00")
CRON_MATCH_NOTIFICATION_START_TIME = os.getenv("CRON_MATCH_NOTIFICATION_START_TIME", "09:00")